version: '3.8'
services:
    backend:
        build: ./backend
        ports:
            - '3001:3001'
        volumes:
            - ./backend:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            - NODE_ENV=development

    frontend:
        build: ./front
        ports:
            - '5173:5173'
        volumes:
            - ./front:/usr/src/app
            - node_modules:/usr/src/app/node_modules
        environment:
            - NODE_ENV=development

volumes:
    node_modules:
